# ==========================================================================
# CRE PROJECT SETTINGS FILE - NexusFi
# ==========================================================================
# Project-specific settings for CRE CLI targets.
# Run CRE commands from this directory (workflows/cre).

# ==========================================================================
staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com

# ==========================================================================
production-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
