# ==========================================================================
# CRE WORKFLOW SETTINGS FILE - NexusFi
# ==========================================================================
# Workflow-specific settings for CRE CLI targets.
# secrets-path: use "./secrets.yaml" if you need secrets (file is gitignored).

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "NexusFi-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "NexusFi-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
